HTML-22 Fix hero
Nidev-lab/perito-siniestros pull request #27
Opened 2022-03-30 18:11 UTC by cajimenez96

2022-03-30 18:46 UTC, Nidev-lab requested changes

2022-03-30 18:46 UTC, Nidev-lab commented on src/components/Hero/Hero.js
> +import { React } from 'react';
Is necessary this?

2022-03-30 18:54 UTC, cajimenez96 commented on src/components/Hero/Hero.js
> +import { React } from 'react';
No. Fixed

2022-03-31 14:19 UTC, alejandrobusi approved these changes
god jobs my braaaa♥

2022-03-31 14:45 UTC, merged