HTML 27 create component forms
Nidev-lab/perito-siniestros pull request #35
Opened 2022-04-09 15:02 UTC by cajimenez96

2022-04-11 20:50 UTC, patoogm requested changes

2022-04-11 20:50 UTC, patoogm commented on src/components/FormsContact/FormsContact.js
> +            <input type="tel" className="form-control" id="tel" placeholder="Ingrese su número de teléfono" />
type='tel' not exist. This correct is type=number.

2022-04-12 12:53 UTC, cajimenez96 commented on src/components/FormsContact/FormsContact.js
> +            <input type="tel" className="form-control" id="tel" placeholder="Ingrese su número de teléfono" />
ok

2022-04-12 15:36 UTC, patoogm requested changes

2022-04-12 15:36 UTC, patoogm commented on src/components/FormsContact/FormsContact.js
> +            <input type="text" className="form-control" id="tel" placeholder="Ingrese su número de teléfono" />
This is incorrect. Phone number is not a text, is a number.

2022-04-12 15:36 UTC, patoogm commented on src/components/FormsContact/FormsContact.js
> +            <input type="text" className="form-control" id="time" value="Lun. a Vie. 9hs-18hs y Sab. 9hs-12hs" disabled />
This type text is incorrect. type="date" is correct

2022-04-12 15:52 UTC, patoogm approved these changes

2022-04-12 16:41 UTC, merged