html 28 review code styled
Nidev-lab/perito-siniestros pull request #37
Opened 2022-04-15 23:45 UTC by cajimenez96

2022-04-18 17:22 UTC, patoogm requested changes

2022-04-18 17:22 UTC, patoogm commented on src/App.css
> +}
Please, enter the end of line

2022-04-18 17:22 UTC, patoogm commented on src/components/Footer/footer.css
> +}
Please, enter the end of line

2022-04-18 17:22 UTC, patoogm commented on src/components/Hero/hero.css
> +}
Please, enter the end of line

2022-04-18 17:22 UTC, patoogm commented on src/components/ManageSinister/ManageSinister.js
> +          <input type="text" className="form-control" id="telefono-tercero" required />
type=text is correct?

2022-04-18 17:22 UTC, patoogm commented on src/components/ManageSinister/ManageSinister.js
> +          <input type="text" className="form-control" id="documento-tercero" required />
type=text is correct?

2022-04-18 17:22 UTC, patoogm commented on src/components/ManageSinister/ManageSinister.js
> +          <input type="text" className="form-control" id="numero-denuncia" required />
type=text is correct?

2022-04-18 17:22 UTC, patoogm commented on src/components/ManageSinister/ManageSinister.js
> +          <input type="text" className="form-control" id="documento-solicitante" required />
type=text is correct?

2022-04-18 17:22 UTC, patoogm commented on src/components/ManageSinister/ManageSinister.js
> +          <input type="text" className="form-control" id="telefono-solicitante" required />
type=text is correct?

2022-04-18 17:22 UTC, patoogm commented on src/components/Navbar/navbar.css
> +}
Please, enter the end of line

2022-04-18 18:19 UTC, Nidev-lab commented
Please, resolve this problem too..
![image](https://user-images.githubusercontent.com/53904695/163854902-4936116e-0f07-4afa-9d52-b3fc742e4af9.png)

2022-04-19 16:09 UTC, patoogm commented on src/components/Footer/Footer.js
> +            <a href="">
Please, correct. href="/#"

2022-04-19 17:30 UTC, patoogm approved these changes

2022-04-19 17:32 UTC, merged